blog/urls.py
# coding:utf-8
"""myblog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required, permission_required


from blog import views 


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^blog/article/(?P<article_id>\d+)$', views.ArticleDetailView.as_view(), name='detail'),
    url(r'^blog/category/(?P<cate_id>\d+)$', views.CategoryView.as_view(), name='category'),
    # 标签对应的 url
    url(r'^tag/(?P<tag_id>\d+)$', views.TagView.as_view(), name='tag'),
    # 文章归档对应的 url
    url(r'^archive/(?P<year>\d+)/(?P<month>\d+)$', views.ArchiveView.as_view(), name='archive'),
    # 评论对应的 URL
    url(r'^article/(?P<article_id>\d+)/comment/$', views.CommentPostView.as_view(), name='comment'),

    url(r'^feeds/$', views.RssFeed(), name="rss"),
    url(r'^about/$', views.AboutView.as_view(), name="about"),
    url(r'^github/$', views.Github, name="github"),

#    url(r'accounts/login/$', 'django.contrib.auth.views.login', {'template_name': login.html}),

    # 登录页面
#    url(r'^login/$', views.login, name="login"),

    #登出
#    url(r'logout/$', views.logout, name="logout"),

]

myblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required, permission_required


from demo import views
import blog


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls', namespace='blog', app_name='blog')),
 #   url(r^blog/', views.IndexView.as_view()),
  #  url(r'^about/', login_required(TemplateView.as_view(template_name="blog/about.html"))),
    url(r'^about/([\w-]+)/$', views.Content_1.as_view()),
    #url(r'^about/$', views.Content.as_view()),
    url(r'^demo/$', views.demo),
]

blog/models.py
# coding:utf-8

import sys
reload(sys)
sys.setdefaultencoding('utf-8')

from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User
from collections import defaultdict



class ArctileManager(models.Manager):
    """
        自定义管理器，继承manager并为其添加一个 archive 方法
    """
    
    def archive(self):
        date_list = Article.objects.datetimes('created_time', 'month', order='DESC')
        
        date_dict = defaultdict(list)  #将字典中的values默认设置为list的实例
        for d in date_list:
            date_dict[d.year].append(d.month)

        return sorted(date_dict.items(), reverse=True)    

class time_stamp(models.Model):
    """
        抽象基类
    """
    # auto_now_add 一次产生  auto_now 每次动作都会更新
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_modified_time = models.DateTimeField('修改时间', auto_now=True)
    class Meta:
        abstract = True


class Article(models.Model):
    """
        文章结构
    """
    STATUS_CHOICES = (
            ('d','Draft'),
            ('p','Published'),
            ('w','Withdrawn'),  #撤回
        )
    title = models.CharField('标题',max_length=70)
    body = models.TextField('正文')
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_modified_time = models.DateTimeField('修改时间', auto_now=True)
    status = models.CharField('文章状态', max_length=1, choices=STATUS_CHOICES)
    abstract = models.CharField('摘要', max_length=54, blank=True, null=True, help_text="可选，为空则提取前54个字符")
    views = models.PositiveIntegerField('浏览量',default=0)
    likes = models.PositiveIntegerField('点赞数',default=0)
    topped = models.BooleanField('置顶', default=False)
    category = models.ForeignKey('Category', verbose_name='分类',null=True,on_delete=models.SET_NULL)
    # blank 为 true，说明网页中填写的字段可以为空，null 为 True 说明 mysql 中的表可以为空
    tags = models.ManyToManyField('Tag', verbose_name='标签云', blank=True)
    #author = models.ForeignKey('auth.User','作者')

    def __str__(self):  # 指明如何表示对象本身，系统一般默认使用 <Article: Article object> ，通过这个函数可以告诉系统使用title字段来表示这个对象
        return self.title
    def __unicode__(self):
        return self.title

    objects = ArctileManager()

    class Meta:
        ordering = ['-last_modified_time']

    # 为 Comment 的 FormView 提供的一个获取 url 的方法
    def get_absolute_url(self):
        # reverse 解析 blog:detail 视图对应的 url  
        return reverse('blog:detail', kwargs={'article_id': self.pk})

class Category(models.Model):
    """
        目录分类
    """

    name = models.CharField('类名',max_length=20)
    created_time = models.DateTimeField('创建时间',auto_now_add=True)
    last_modified_time = models.DateTimeField('修改时间',auto_now=True)

    def __str__(self):
        return self.name
    def __unicode__(self):
        return self.name

class Tag(models.Model):
    """
        标签云
    """

    name = models.CharField('标签名', max_length=20) 
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_modified_time = models.DateTimeField('修改时间', auto_now_add=True)

    def __str__(self):
        return self.name 
    def __unicode__(self):
        return self.name 


class BlogComment(models.Model):
    """
        评论信息
    """
    user_name = models.CharField('评论者名字', max_length=100)
    user_email = models.EmailField('评论者邮箱', max_length=255)
    body = models.TextField('评论内容')
    created_time = models.DateTimeField('发表评论时间', auto_now_add=True)
    article = models.ForeignKey('Article', verbose_name='评论文章', on_delete=models.CASCADE)
    website = models.URLField('站点信息', blank=True, null=True)  #检查 url 可用性

    def __str__(self):
        return self.body[:20]  

    def __unicode__(self):
        return self.body[:20]

blog/forms.py
#!/usr/bin/env python
# coding:utf-8

from django import forms
from .models import Article, BlogComment


class BlogCommentForm(forms.ModelForm):
    """
        评论表单
    """
    class Meta:
        """
            指定一些 Meta 选项以改变 form 被渲染后的样式
        """
        model = BlogComment #指定 form 关联的 model
        # 需要渲染的字段
        fields = ['user_name', 'user_email', 'body', 'website']
        
        widgets = {
            # 为要渲染的字段添加 css 样式
            # 例如 user_name 渲染后的html组件如下：
            # <input type="text" class="form-control" placeholder="Username" aria-describedby="sizing-addon1">


            'user_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': "请输入昵称",
                'aria-describedby': "sizing-addonl",
            }),
            'user_email': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': '请输入邮箱',
                'aria-describedby': 'sizing-addonl',
            }),
            'website': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': '请输入网址',
                'aria-describedby': 'sizing-addonl',
            }),
            'body': forms.Textarea(attrs={
                'placeholder': '说点什么吧...',
            }),

        }
        

blog/views.py
# coding:utf-8

from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .forms import BlogCommentForm
from django.views.generic import ListView, DetailView, FormView, TemplateView
from blog.models import Article, Category, Tag, BlogComment
from django.contrib.syndication.views import Feed
from django.http import HttpResponse
import markdown2


class IndexView(ListView):  
    """
        首页视图函数，继承 ListView ，展示从数据库中获取的文章列表   
    """
    template_name = "blog/index.html"
    context_object_name = "article_list"

    def get_queryset(self):
        """
            重写 get_queryset 方法，取出发表的文章并转换文章格式
        """
        article_list = Article.objects.filter(status='p')
        for article in article_list:
            article.body = markdown2.markdown(article.body, extras=['fenced-code-blocks'], )
        return article_list

    def get_context_data(self, **kwargs):
        kwargs['category_list'] = Category.objects.all().order_by('name')

        # 使用自定义的 manager ，调用 archive 方法，
        kwargs['date_archive'] = Article.objects.archive()
        kwargs['tag_list'] = Tag.objects.all().order_by('name')
        return super(IndexView, self).get_context_data(**kwargs)


class ArticleDetailView(DetailView):
    """
        文章详情页
    """

    model = Article
    template_name = 'blog/detail.html'
    context_object_name = "article"
    # 传递到模板文件中的变量

    pk_url_kwarg = 'article_id'
    # 在 urlpattern 中定义的


    def get_object(self, queryset=None):
        """ 
            错误处理，请求文章不存在
        """
        try:
            obj = super(ArticleDetailView, self).get_object()  #重写 get_object
            obj.body = markdown2.markdown(obj.body, extras=['fenced-code-blocks'], )
        except Exception as e:
            obj="Article  is NotFound!"
            return obj
        return obj  

    # 增加 form 到 context
    def get_context_data(self, **kwargs):
        kwargs['comment_list'] = self.object.blogcomment_set.all()  #获取评论
        kwargs['form'] = BlogCommentForm()
        kwargs['comment_count'] = self.object.blogcomment_set.count() #获取评论数量
        return super(ArticleDetailView, self).get_context_data(**kwargs)


class CategoryView(ListView):
    """
        分类视图，点击某个分类，展示分类下的所有文章
    """

    template_name = "blog/index.html"
    context_object_name = "article_list"

    def get_queryset(self):
        article_list = Article.objects.filter(category=self.kwargs['cate_id'],status='p')

        for article in article_list:
            article.body = markdown2.markdown(article.body, extras=['fenced-code-blocks'], )
        return article_list

    def get_context_data(self, **kwargs):
        kwargs['category_list'] = Category.objects.all().order_by('name')
        return super(CategoryView, self).get_context_data(**kwargs)


class TagView(ListView):
    """
        标签云，获取标签下的文章
    """
    template_name = "blog/index.html"
    context_object_name = "article_list"

    def get_queryset(self):
        """
            获取指定标签下的全部文章
        """
        
        article_list = Article.objects.filter(tags=self.kwargs['tag_id'], status='p')
        for article in article_list:
            article.body = markdown2.markdown(article.body, extras=['fenced-code-blocks'], )
        return article_list

    def get_context_data(self, **kwargs):
        kwargs['tar_id'] = Tag.objects.all().order_by('name')
        return super(TagView, self).get_context_data(**kwargs)

class ArchiveView(ListView):
    template_name = 'blog/index.html'
    context_object_name = 'article_list'
    
    
    def get_queryset(self): 
        # 将从 url 传入的参数year 和 month 转换为 int
        year = int(self.kwargs['year'])
        month = int(self.kwargs['month'])

        article_list = Article.objects.filter(created_time__year=year, created_time__month=month)
        for article in article_list:
            article.body = markdown2.markdown(article.body, extras=['fenced-code-blocks'], )
        return article_list

class CommentPostView(FormView):
    form_class = BlogCommentForm  #指定使用的 form
    template_name = 'blog/detail.html'  #指定使用的模板文件

    def form_valid(self, form):
        """
            提交的数据合法
        """
        #get_object_or_404() 函数需要一个 Django 模型类作为第一个参数以及 一些关键字参数，它将这些参数传递给模型管理器中的 get() 函数。 若对象不存在时就抛出 Http404 异常。
        # 首先根据 url 传入的文章 id ，获取相应的文章
        target_article = get_object_or_404(Article, pk=self.kwargs['article_id'])


        comment = form.save(commit=False)   #实例化一个 comment 对象，但是不保存评论
        comment.article = target_article    # 为 comment 关联一个文章,即添加一个属性
        comment.save()                      # 保存评论的内容

        # 评论完成后返回到被评论的文章页面, get_obsolute_url 是 Article 新增的一个方法方便,获取文章对用的 url
        self.success_url = target_article.get_absolute_url()  
        return HttpResponseRedirect(self.success_url)

    def form_invalid(self, form):
        """
            提交的数据不合法
        """
        
        target_article = get_object_or_404(Article, pk=self.kwargs['article_id'])
        
        # 不保存评论，返回原来的文章页面
        return render(self.request, 'blog/detail.html', {
            'form': form,
            'article': target_article,
            'comment_list': target_article.blogcomment_set.all(),
            #'comment_count': target_article.blogcomment_set.count(),
        })

class RssFeed(Feed):
    """
        RSS 订阅
    """
    title = "RSS Feed - article"
    link = "/feeds/"
    description = "RSS feed - blog posts"

    def items(self):
        return Article.objects.order_by("-created_time")
    def item_title(self, item):
        return item.title
    def item_description(self, item):
        return item.abstract
    def item_pubdate(self, item):
        return item.created_time

class LoginView(TemplateView):
    """
        登录页面
    """
    template_name = 'blog/login.html'
    def form_valid(self):
        pass
    def get_context_data(self, **kwargs):
        pass

def Github(request):
    """
        Github
    """
    return HttpResponseRedirect('https://github.com/strugglingyouth')


class AboutView(ListView):
    """
        About me
    """
    template_name = "blog/about.html"
    context_object_name = "article_about_me"

    def get_queryset(self):
        article_about_me = Article.objects.filter(category__name='about',status='w')
        return article_about_me   

blog/templates/blog/about.html
{% extends 'base.html' %}
{% block content %}
 <div class="container">
        <div class="row">
            <div id="bd" class="wrp clear-fix">
                <div id="main">
                    <div id="detail-title">
                    </div>
                    <div id="post-1951"
                         class="post-1951 post type-post status-publish format-standard hentry category-meida-report" style="height:800px">
                        
                        <div class="post-bd">
                        <p>
                            正在建设中。。。<br/>
                            
                            <br/>
                            <br/>
                            <br/>
                            <br/>

                        </p>    
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>   

{% endblock %}

blog/templates/blog/comment.html
<div class="comment">
    <div class="comment-main">
        <p class="head">评论详情</p>
        <form method="post" action="{% url 'blog:comment' article.pk %}">
            {% csrf_token %}
            <div class="row">
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <br>
                {% endfor %}
            </div>
            <button type="submit" class="com-button">评论</button>
        </form>
        <p class="comment-count">共{{ comment_count }}条评论</p>
        <hr>
        {% for comment in comment_list %}
            <div class="main-content">
{#                <img src="月英1.jpg" class="user-avatar">#}
                <span class="user-nickname">{{ comment.user_name }}</span>
                <time class="time">{{ comment.created_time }}</time>
                <div class="comment-content">
                    {{ comment.body }}
                </div>
{#                <a href="">回复</a>#}
            </div>
            <hr>
        {% endfor %}
    </div>
</div>

blog/templates/blog/detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div id="bd" class="wrp clear-fix">
                <div id="main">
                    <div id="detail-title">
                        <ul id="single-nav">
                            <li><a href="{% url 'blog:index' %}">首页</a></li>
                            <li>&gt;</li>
                            <li>
                                <ul class="post-categories">
                                    <li><a href="" title=""
                                           rel="category">{{ article.category.name }}</a>
                                    </li>
                                </ul>
                            </li>
                            <li>&gt;</li>
                            <li class="title-active"><a href="{% url 'blog:detail' article.pk %}"
                                                        rel="bookmark">{{ article.title }}</a>
                            </li>
                        </ul>
                    </div>
                    <div id="post-1951"
                         class="post-1951 post type-post status-publish format-standard hentry category-meida-report">
                        <div class="post-hd">
                            <h1 class="title">{{ article.title }}</h1>
                        </div>
                        <div class="date-read">
                            <i class="icon-date"></i><span
                                class="date">{{ article.last_modified_time|date:"Y年n月d日" }}</span>
                        </div>
                        <div class="post-bd">
                            {{ article.body |safe }}
                        </div>
                    </div>
                </div>
            </div>
            {% include 'blog/comment.html' %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% block content %}
    <div id="banner" class="noselect"></div>

    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div id="category" class="noselect">
                    <div id="category-title">
                        <ul>
                            <li>分类：</li>
                            {% for category in category_list %}
                                <li class="cat-item"><a
                                        href="{% url 'blog:category' category.pk %}">{{ category.name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

                <div id="bd" class="wrp clear-fix">
                    <div id="main">
                        {% load paginate_tags %}
                        {% paginate article_list 7 %} <!-- 每页的文章数 -->
                        {% for article in article_list %}
                            <div class="post">
                                <div class="post-hd">
                                    <h1 class="title"><a
                                            href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a></h1>
                                </div>
                                <div class="post-bd">
                                    <!-- 	<p><a href=""><img src="" alt=""></a></p> -->
                                    <p>{{ article.abstract }}</p>
                                    <p>{{ article.body|truncatechars:100 }}</p>
                                    <p><a href="" class="more-link"></a></p>
                                </div>
                                <div class="post-ft">
                                    <a href="{% url 'blog:detail' article.id %}" class="more">阅读全文>></a>
                                    <i class="icon-date"></i>
                                    <span class="date">{{ article.last_modified_time|date:"Y年n月d日" }}</span>
                                </div>
                            </div>
                        {% endfor %}
                        {% include 'blog/pagination.html' %}
                    </div>
                </div>
            </div>

            <div class="col-lg-3">
                <!-- tags -->
                <h3>标签:</h3>
                <div class="list-group">
                    {% for tag in tag_list %}
                        <a href="{% url 'blog:tag' tag.pk %}" class="list-group-item"><span
                                class="badge"></span>{{ tag.name }}</a>
                    {% endfor %}
                </div>

                <!-- archive -->
                <h3>文章归档：</h3>
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                    {% for year,months in date_archive %}
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="heading{{ forloop.counter }}">
                                <h4 class="panel-title">
                                    <a role="button" data-toggle="collapse" data-parent="#accordion"
                                       href="#collapse{{ forloop.counter }}"
                                       aria-expanded="true" aria-controls="collapse{{ forloop.counter }}">
                                        {{ year }} 年
                                    </a>
                                </h4>
                            </div>
                            <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse in" role="tabpanel"
                                 aria-labelledby="heading{{ forloop.counter }}">
                                <div class="panel-body">
                                    {% for month in months %}
                                        <a href="{% url 'blog:archive' year month %}"><p>{{ month }} 月</p></a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/pagination.html
<div id="pagenavi" class="noselect">
    {% if article_list.has_previous %}
        <a class="previous-page" href="?page={{ article_list.previous_page_number }}">
            <span class="icon-previous"></span>上一页
        </a>
    {% endif %}

    {% if first_page == current_page %}
        <span class="first-page current">1</span>
    {% else %}
        <a href="?page=1" class="first-page">1</a>
    {% endif %}

    {% if pages_first > 2 %}
        <span>...</span>
    {% endif %}

    {% for page in pages %}
        {% if page == current_page %}
            <span class="current">{{ page }}</span>
        {% else %}
            <a href="?page={{ page }}">{{ page }}</a>
        {% endif %}
    {% endfor %}

    {% if pages_last < last_page %}
        <span>...</span>
    {% endif %}

    {% if last_page != 1 %}
        {% if last_page == current_page %}
            <span class="current">{{ last_page }}</span>
        {% else %}
            <a href="?page={{ last_page }}">{{ last_page }}</a>
        {% endif %}
    {% endif %}

    {% if article_list.has_next %}
        <a class="next-page" href="?page={{ article_list.next_page_number }}">
            下一页<span class="icon-next"></span>
        </a>
    {% endif %}
</div>